version: '3.8'

services:
  ai_video_editor:
    build:
      context: .
      dockerfile: Dockerfile.railway
      args:  # Pass all environment variables to the build context
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
        SMTP_FROM: ${SMTP_FROM}
        DATABASE_URL: ${DATABASE_URL}
        APP_URL: ${APP_URL}
        SVIX_URL: ${SVIX_URL}
        SVIX_API_KEY: ${SVIX_API_KEY}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        NEXT_PUBLIC_DARK_MODE: ${NEXT_PUBLIC_DARK_MODE}
        PORT: ${PORT}
    env_file:  # Load runtime environment variables from .env file
      - .env
    ports:
      - "4002:4002"
    environment:  # Declare runtime environment variables
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      DATABASE_URL: ${DATABASE_URL}
      APP_URL: ${APP_URL}
      SVIX_URL: ${SVIX_URL}
      SVIX_API_KEY: ${SVIX_API_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NEXT_PUBLIC_DARK_MODE: ${NEXT_PUBLIC_DARK_MODE}
      PORT: ${PORT}
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
