[phases.setup]
aptPkgs = ["wget", "unzip", "libc6"]

[phases.build]
commands = [
  "wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-essentials.zip",
  "unzip ffmpeg-release-essentials.zip",
  "mv ffmpeg-*-static/ffmpeg /usr/local/bin/ffmpeg",
  "mv ffmpeg-*-static/ffprobe /usr/local/bin/ffprobe",
  "rm -rf ffmpeg-release-essentials.zip ffmpeg-*-static"
]
